"""empty message

Revision ID: 44385f3b8974
Revises: 36ca71463257
Create Date: 2025-04-10 20:51:10.994363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44385f3b8974'
down_revision = '36ca71463257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
